#!/bin/bash
# Dumont Cloud CLI - Quick Reference (Natural Commands)

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║         🚀 DUMONT CLOUD CLI - NATURAL COMMANDS GUIDE                 ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "🔐 AUTHENTICATION:"
echo ""
echo "  dumont auth login user@email.com password"
echo "  dumont auth me"
echo "  dumont auth logout"
echo ""
echo "💻 INSTANCES:"
echo ""
echo "  # List all instances"
echo "  dumont instance list"
echo ""
echo "  # Create instance with AI wizard"
echo "  dumont instance create wizard rtx4090"
echo ""
echo "  # Create instance manually"
echo "  dumont instance create rtx4090"
echo "  dumont instance create rtx4090 num_gpus=2"
echo "  dumont instance create 'a100 80gb' num_gpus=4"
echo ""
echo "  # Get instance details"
echo "  dumont instance get 12345"
echo ""
echo "  # Control instances"
echo "  dumont instance pause 12345"
echo "  dumont instance resume 12345"
echo "  dumont instance wake 12345"
echo "  dumont instance delete 12345"
echo ""
echo "  # Migration"
echo "  dumont instance migrate 12345"
echo ""
echo "💾 SNAPSHOTS:"
echo ""
echo "  # List snapshots"
echo "  dumont snapshot list"
echo ""
echo "  # Create snapshot"
echo "  dumont snapshot create backup-name instance_id=12345"
echo ""
echo "  # Restore snapshot"
echo "  dumont snapshot restore snapshot_id=abc123 instance_id=12345"
echo ""
echo "⚙️  SETTINGS:"
echo ""
echo "  # View settings"
echo "  dumont setting list"
echo ""
echo "  # Update settings"
echo "  dumont setting update vast_api_key=YOUR_KEY"
echo ""
echo "📊 METRICS & MONITORING:"
echo ""
echo "  # Dashboard metrics"
echo "  dumont metric dashboard"
echo ""
echo "  # Cost metrics"
echo "  dumont metric cost"
echo ""
echo "🤖 AI FEATURES:"
echo ""
echo "  # AI Wizard analysis"
echo "  dumont ai-wizard analyze"
echo ""
echo "  # Get GPU recommendations"
echo "  dumont advisor recommend"
echo ""
echo "💰 SAVINGS CALCULATOR:"
echo ""
echo "  # Calculate savings"
echo "  dumont saving calculate"
echo ""
echo "🔥 QUICK SHORTCUTS (after source ~/.bashrc):"
echo ""
echo "  dmlogin user@email.com password  # Login"
echo "  dmme                             # Check auth"
echo "  dmls                             # List instances"
echo "  dmcreate wizard rtx4090          # Create with wizard"
echo "  dmget 12345                      # Get instance"
echo "  dmrm 12345                       # Delete instance"
echo "  dmsnap                           # List snapshots"
echo ""
echo "💡 TIPS:"
echo ""
echo "  • Commands work from ANY directory"
echo "  • Token saved automatically after login"
echo "  • Use 'wizard' keyword for AI-assisted creation"
echo "  • Key=value syntax for parameters"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
